name: "Setup AArch64 Builder SSH"
description: "Configures SSH for accessing the remote AArch64 machine"

inputs:
  ssh-key:
    description: "SSH key for the aarch64 builder"
    required: true

runs:
  using: "composite"
  steps:
    - name: setup-aarch64-ssh
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo 'aarch64-build-box,aarch64.nixos.community,147.75.77.190 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMUTz5i9u5H2FHNAmZJyoJfIGyUm/HfGhfwnc142L3ds' >> ~/.ssh/known_hosts
        chmod 0600 ~/.ssh/known_hosts
        echo "${{ inputs.ssh-key }}" > ~/.ssh/aarch64-builder-ed25519
        chmod 0600 ~/.ssh/aarch64-builder-ed25519
        cat <<-'EOF' > ~/.ssh/config
        Host aarch64.nixos.community 147.28.143.250
            User lovesegfault
            IdentitiesOnly yes
            IdentityFile ~/.ssh/aarch64-builder-ed25519
            ControlMaster auto
            ControlPath ~/.ssh/ssh-%r@%h:%p
            ControlPersist 30m
            ForwardAgent no
            ForwardX11 no
            ForwardX11Trusted no
            ServerAliveCountMax 5
            ServerAliveInterval 60
        EOF
        kernel_name="$(ssh -T aarch64.nixos.community uname -s)"
        [[ "$kernel_name" == "Linux" ]] || exit 1
