# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c7467d00-b7c6-41c7-abda-50713976d18e";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."nixos".device = "/dev/disk/by-uuid/0951bcc3-a1b4-49cc-aca8-5a1eaeffa018";

  fileSystems."/srv" =
    { device = "/dev/disk/by-uuid/c7467d00-b7c6-41c7-abda-50713976d18e";
      fsType = "btrfs";
      options = [ "subvol=srv" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/c7467d00-b7c6-41c7-abda-50713976d18e";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4EA4-0858";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/0d052256-6979-4b33-a0bf-2ca2b51e4d4a"; }
    ];

  nix.maxJobs = lib.mkDefault 12;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
