{ config, pkgs, lib, ... }:
{
  config.home.packages = with pkgs; [
    arcanist
    beets
    exa
    fzf
    gnupg
    lynx
    nix-index
    ripgrep
    rustup
    skim
    travis
    (python3.withPackages(ps: with ps; [
      python-language-server
      ps.pyls-mypy
      ps.pyls-isort
      ps.pyls-black
    ]))
    llvmPackages_latest.clang-unwrapped
  ] ++ lib.optionals (config.isDesktop) [
    alacritty
    pantheon.elementary-files
    feh
    font-awesome
    gopass
    grim
    hack-font
    i3status-rust
    imagemagick
    jetbrains.clion
    libnotify
    light
    lollypop
    mako
    passff-host
    pavucontrol
    pinentry_gnome
    playerctl
    powerline-fonts
    shotwell
    slack
    slurp
    spotify
    sublime3-dev
    sway
    swayidle
    swaylock
    texlive.combined.scheme-full
    vlc
    vscode
    weechat
    wl-clipboard
    xclip
    xdg_utils
    xorg.setxkbmap
    xorg.xhost
    xsel
    yubikey-personalization-gui
    yubioath-desktop
    zathura
    zoom-us
  ];

}
