{ config, pkgs, lib, ... }:
{
  config.home.packages = with pkgs; lib.mkMerge [
    [
      arcanist
      beets
      exa
      fzf
      gist
      gnupg
      llvmPackages_latest.clang-unwrapped
      lynx
      nix-index
      (python3.withPackages(ps: with ps; [
        python-language-server
        ps.pyls-mypy
        ps.pyls-isort
        ps.pyls-black
      ]))
      ripgrep
      rustup
      skim
      travis
      vimpager-latest
    ]

    (lib.mkIf config.isDesktop [
      alacritty
      feh
      font-awesome
      gopass
      grim
      hack-font
      i3status-rust
      imagemagick
      jetbrains.clion
      libnotify
      light
      lollypop
      mako
      pantheon.elementary-files
      passff-host
      pavucontrol
      pinentry_gnome
      playerctl
      powerline-fonts
      qutebrowser
      shotwell
      slack
      slurp
      spotify
      sublime3-dev
      sway
      swayidle
      swaylock
      texlive.combined.scheme-full
      vlc
      vscode
      weechat
      wl-clipboard
      xclip
      xdg_utils
      xorg.setxkbmap
      xorg.xhost
      xsel
      yubikey-personalization-gui
      yubioath-desktop
      zathura
      zoom-us
    ])
  ];
}
