name: "Setup Nix"
description: "Sets up Nix, Cachix, and remote builders"

inputs:
  cachix:
    description: "Whether to setup cachix"
    required: true
    default: true
    type: boolean
  cachix-auth-token:
    description: "Auth token for cachix"
    required: false
  github-token:
    description: "A GitHub token for making authenticated requests"
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - uses: DeterminateSystems/nix-installer-action@v4
      with:
        nix-installer-tag: "v0.12.0"
        extra-conf: |
          auto-optimise-store = true
          accept-flake-config = true
          builders-use-substitutes = true
        github-token: ${{ inputs.github-token }}
    - uses: cachix/cachix-action@v12
      if: ${{ inputs.cachix == 'true' }}
      with:
        name: nix-config
        authToken: ${{ inputs.cachix-auth-token }}
